language: php

dist: trusty
sudo: false

git:
    depth: 1

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: SYMFONY_VERSION=2.7.*
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 7.0
          env: PHP_CS_FIXER=true
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 7.2
          env: SYMFONY_VERSION=3.2.* TEST_COVERAGE=true
        - php: 7.2
          env: SYMFONY_VERSION=4.1.* DEPENDENCIES=dev
        - php: nightly
          env: COMPOSER_UPDATE_FLAGS=--ignore-platform-reqs
    allow_failures:
        - php: nightly
        - php: 7.2
          env: SYMFONY_VERSION=4.1.* DEPENDENCIES=dev
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php_cs.cache
        - vendor/

before_install:
    - if [ ${DEPENDENCIES} = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [[ ${TEST_COVERAGE} != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --dev --no-update; fi;

install: composer update --prefer-source --no-interaction --optimize-autoloader ${COMPOSER_UPDATE_FLAGS}

script:
    - bin/phpunit --debug $( if [ $TEST_COVERAGE = true ]; then echo "-d xdebug.max_nesting_level=1000 --coverage-clover=build/logs/clover.xml"; fi; )
    - if [ ${PHP_CS_FIXER} = true ]; then composer require "friendsofphp/php-cs-fixer:^2.0" && bin/php-cs-fixer fix --diff --dry-run -v; fi;

after_script:
    - if [ ${TEST_COVERAGE} = true ]; then composer require "satooshi/php-coveralls:^1.0" && travis_retry php bin/coveralls -v; fi
