services:
    overblog_dataloader.cache_map:
        shared: false
        public: false
        class: Overblog\DataLoader\CacheMap

    overblog_dataloader.react_promise_adapter:
        public: false
        class: Overblog\PromiseAdapter\Adapter\ReactPromiseAdapter

    overblog_dataloader.guzzle_http_promise_adapter:
        public: false
        class: Overblog\PromiseAdapter\Adapter\GuzzleHttpPromiseAdapter

    overblog_dataloader.webonyx_graphql_sync_promise_adapter:
        public: false
        class: Overblog\PromiseAdapter\Adapter\WebonyxGraphQLSyncPromiseAdapter
        arguments:
            - "@webonyx_graphql.sync_promise_adapter"

    webonyx_graphql.sync_promise_adapter:
        class: Overblog\DataLoader\Promise\Adapter\Webonyx\GraphQL\SyncPromiseAdapter
